apps/backend/src/reconciliation/pos-reconciliation.service.ts

Objective: 
Fix bug that does not mark `match=true` for certain deposits when they were matched. 
Issue - reuse of deposits for matching after they were already used for matches!

[CHORE] Fix heuristic bug on eager matching

---

api-gateway/payment-noplugins.yaml

Aidan Cope: "In our test environment we have a global request-transformer plugin that adjusts the Host to align with what would be in production if preserve_host=true. This will only create an issue in our test instance, not our prod instance. To get around this add a 'request-transformer' plugin to your Service - so that it takes precedence over the global one."

[CHORE] Add request-transformer to payment-noplugins.yaml

---

apps/backend/src/lambdas/utils/parseTDI.ts
apps/backend/src/parse/parse.controller.ts
apps/backend/src/parse/parse.service.ts

[CCFPCM-0375](https://bcdevex.atlassian.net/browse/CCFPCM-0375)
Objective: 
Removed file upload for testing json (testing can now be done in the DB and previous changes have broken this endpoint). Left TDI parsing in place as parsed TDI in json format may still be useful in testing. 
Fixed swapped metadata fields on TDI34 parsing

[CCFPCM-0375] file parser

---

apps/backend/src/constants.ts
apps/backend/src/lambdas/parseFlatFile.ts
apps/backend/src/lambdas/parser.ts
apps/backend/src/lambdas/utils/parseTDI.ts
apps/backend/src/parse/parse.controller.ts
apps/backend/src/parse/parse.service.ts

[bugfix](https://bcdevex.atlassian.net/browse/CCFPCM-0000)
Objective: 
Created an interface for the required file parsing arguments

[FIX] interface for parsing arguments for parse lambda

---

apps/backend/sample-files/transaction.json
apps/backend/src/database/migrations/1677697814581-migration.ts
apps/backend/src/lambdas/utils/parseGarms.ts
apps/backend/src/transaction/dto/payment.dto.ts
apps/backend/src/transaction/entities/payment.entity.ts
apps/backend/src/transaction/interface/sbc_garms.ts

[CCFPCM-0393](https://bcdevex.atlassian.net/browse/CCFPCM-0393)
- Account for USD during reconciliation
- Add column to record the calculated CAD amount in the case of non CAD payments (based on the provided exchange rate)
- Write migrations to include this column with the proper amounts in the db
- Write migration to update the current garms SBC exchange rate format to a standard exchange rate format. (Percentage, from foreign currency to CAD, not vice versa... ie: USD -> CAD = 1.34)
- Update garms parsing for proper exchange rate format
- Update API spec to validate proper exchange rate format
- Update cash reconciliation to use the calculated amount
- Add a getter to the payment class to return adjusted amount if it is exists, or, amount if not, and use this value for …

[CCFPCM-0393] non CAD cash

---

apps/backend/src/database/migrations/1677643656658-migration.ts
apps/backend/src/database/migrations/1677775665682-migration.ts
apps/backend/src/database/migrations/1677783207700-migration.ts
apps/backend/src/database/migrations/2524636800000-migration.ts
apps/backend/src/database/migrations/2524636800001-migration.ts
apps/backend/src/deposits/cash-deposit.service.ts
apps/backend/src/deposits/entities/cash-deposit.entity.ts
apps/backend/src/flat-files/tdi17/TDI17Details.ts
apps/backend/src/lambdas/reconcile.ts
apps/backend/src/location/location.service.ts

[CCFPCM-0000](https://bcdevex.atlassian.net/browse/CCFPCM-0000)
Objective: 
TDI 17 “transaction type“ and “location_id“ should be a single column/field called pt_location_id. 
Update this in the TDI17 parser, update cash match location lookup, and write migrations to fix this issue.

[CCFPCM-0404] TDI 17 location id -> pt_location_id

---

apps/backend/fixtures/lambda/reconcile.json
apps/backend/src/lambdas/reconcile.ts
apps/backend/src/location/location.service.ts
apps/backend/src/reporting/reporting.service.ts

[FIX](https://bcdevex.atlassian.net/browse/CCFPCM-0000)
- When the column for the pt_location_ids in the cash deposit table was last updated, the logic for the location lookup for cash reconciliation had an error if a location id was passed in with the reconciliation event. If a location_id is passed in to the recon event, this location_id should be used to lookup pt_location_ids, rather than expecting a pt_location_id to be passed in with the event.

[FIX] cash location_ids

---

apps/backend/src/deposits/cash-deposit.service.ts
apps/backend/src/deposits/pos-deposit.service.ts
apps/backend/src/lambdas/reconcile.ts
apps/backend/src/reconciliation/cash-reconciliation.service.ts
apps/backend/src/reconciliation/pos-reconciliation.service.ts
apps/backend/src/reporting/reporting.service.ts
apps/backend/src/transaction/payment.service.ts
apps/backend/src/transaction/transaction.service.ts

- pos_deposit id was not being recorded. 
- added in second layer of matching to match by day, after matching by 5 minutes initially for POS.
- cleaned up the reconcile lambda logging
- (attempted) to simplify some of the pos reconciliation functions for easier unit testing
- removed unused or unnecessary functions

[FIX] pos-deposit-match

---

apps/backend/fixtures/lambda/report.json
apps/backend/src/reporting/reporting.service.ts
apps/backend/src/reporting/styles.ts

[CCFPCM-0445](https://bcdevex.atlassian.net/browse/CCFPCM-0445)
Show only cash deposits which were made on the date that the report is being generated.  If there is a deposit on that date, show the deposit information as well as the corresponding cash payments. 
ALL cash payments which are PENDING or IN_PROGRESS should also be shown on the report which occurred between the report json "period.to" and "period.from" dates
Exceptions and Matches should appear on the report only once, on the corresponding deposit date which matches the report "config.period.to" date.

[CCFPCM-0445]: Update reporting with new criteria for cash

---

apps/backend/test/mocks/classes/pos_deposit_mock.ts
apps/backend/test/mocks/classes/transaction_mock.ts
apps/backend/test/unit/deposits/pos_deposit.service.spec.ts
apps/backend/test/unit/reconciliation/helpers.ts
apps/backend/test/unit/reconciliation/pos-reconciliation.spec.ts

[CCFPCM-0419](https://bcdevex.atlassian.net/browse/CCFPCM-0419)
Objective:
- POS reconciliation service unit tests
- POS deposit unit tests

[CCFPCM-419] pos reconciliation service and pos deposit service unit tests

---

apps/backend/fixtures/lambda/reconcile.json
apps/backend/fixtures/lambda/report.json
apps/backend/src/reporting/details-report.service.ts
apps/backend/src/reporting/reporting.service.ts
apps/backend/src/transaction/payment.service.ts

Objective: 
- date on summary/details/cas report should show the "to_date" when generating a report
- reports should not generate on the weekend
- page2 (details report): 
- pos should show only pos deposits for the "to_date"
- payments should show only pos payments for the "to_date", except in the case of a match (a payment may show on a different date if it matches 1:1 with a pos deposit from the report date)

[FIX]: report updates for heuristic 3 changes

---

apps/backend/src/reconciliation/pos-reconciliation.service.ts
apps/backend/test/unit/reconciliation/helpers.ts
apps/backend/test/unit/reconciliation/pos-reconciliation.spec.ts

[CCFPCM-0526](https://bcdevex.atlassian.net/browse/CCFPCM-0526)
Objective: 
- only match round three POS if deposit date is before payment date

[CCFPCM-0526] bugfix - heuristic 3

---

apps/backend/fixtures/lambda/report.json
apps/backend/package.json
apps/backend/src/common/transformers/numericColumnTransformer.ts
apps/backend/src/constants.ts
apps/backend/src/deposits/entities/cash-deposit.entity.ts
apps/backend/src/deposits/entities/pos-deposit.entity.ts
apps/backend/src/lambdas/utils/parseGarms.ts
apps/backend/src/reconciliation/cash-reconciliation.service.ts
apps/backend/src/reconciliation/pos-reconciliation.service.ts
apps/backend/src/reconciliation/types/interface.ts
apps/backend/src/reporting/cas-report/cas-report.ts
apps/backend/src/reporting/detailed-report/cash-details-report.ts
apps/backend/src/reporting/details-report.service.ts
apps/backend/src/reporting/reporting.service.ts
apps/backend/src/transaction/entities/payment.entity.ts
apps/backend/src/transaction/entities/transaction.entity.ts
apps/backend/src/transaction/payment.service.ts
apps/backend/test/mocks/mocks.cash.spec.ts
apps/backend/test/mocks/mocks.ts
apps/backend/test/unit/reconciliation/cash-reconciliation.spec.ts
apps/backend/test/unit/reconciliation/helpers.ts
apps/backend/test/unit/reconciliation/pos-reconciliation.spec.ts
yarn.lock

[CCFPCM-0524](https://bcdevex.atlassian.net/browse/CCFPCM-0524)
Objective: 
- when aggregating payment and deposit sums we are losing .001 of a decimal in some cases, which is causing a false exception when matching for pos round four heuristics as well as cash payments to deposits
- implement decimal.js library to use the decimal type when summing the payment/deposit totals

[CCFPCM-0524] floating point decimal type precision loss bug

---

apps/backend/src/parse/parse.controller.ts
apps/backend/src/parse/parse.service.ts

Objective: 
The success handler was returning true when it shouldn't. This now does not default to that.
Also, some api body schemas

[FIX] ingestion success logic can now be false

---

apps/backend/fixtures/lambda/reconcile.json
apps/backend/src/lambdas/reconcile.ts
apps/backend/src/reconciliation/types/interface.ts

[CCFPCM-525](https://bcdevex.atlassian.net/browse/CCFPCM-525)
Objective: 
As part of AC3 (though I might try to move that AC elsewhere), we want to prevent the reconciler from running if files haven't been uploaded today. Unfortunately, this is an issue if we're running the reconciler for different scenarios. For example, we haven't uploaded the files today yet, but we're testing the reconciler for the past.
One interesting thing. We can only run the reconciler with a max date of "yesterday". However, uploading files adds them in for "today", for data "yesterday". This will be addressed in future tickets, potentially [491](https://bcdevex.atlassian.net/browse/CCFPCM-491)

[CCFPCM-525] reconcile only if there are valid files uploaded today

---

apps/backend/src/deposits/entities/cash-deposit.entity.ts
apps/backend/src/deposits/entities/pos-deposit.entity.ts
apps/backend/src/lambdas/parser.ts
apps/backend/src/transaction/entities/transaction.entity.ts

Objective: 
This optimizes the parsing for the whole dataset. In my machine, it took under 12 minutes until July. May still need a longer term solution if this builds up to, say, a year's worth of data.
The validation itself turned out to not be the issue, but the fact that relationships in TypeORM can be non performant when you're talking about thousands of entries at once.
Utilizes this TypeORM trick 
https://github.com/typeorm/typeorm/blob/master/docs/relations-faq.md#how-to-use-relation-id-without-joining-relation

[CHORE] Optimizing parsing by utilizing relation ids

---

apps/backend/src/database/datasource.ts
apps/backend/src/database/migrations/1689666205003-required-files-migration.ts
apps/backend/src/database/migrations/1689667429932-alert-destination-migration.ts
apps/backend/src/lambdas/parser.ts
apps/backend/src/notification/entities/alert-destination.entity.ts
apps/backend/src/notification/mail.service.ts
apps/backend/src/notification/notification.module.ts
apps/backend/src/parse/entities/file-ingestion-rules.entity.ts
apps/backend/src/parse/entities/program-required-file.entity.ts
apps/backend/src/parse/parse.controller.ts
apps/backend/src/parse/parse.module.ts
apps/backend/src/parse/parse.service.ts
apps/backend/test/mocks/classes/file_ingestion_rules_mock.ts
apps/backend/test/mocks/classes/required_file_mock.ts
apps/backend/test/unit/parsing/parse-service.spec.ts

[CCFPCM-491](https://bcdevex.atlassian.net/browse/CCFPCM-491)
Objective: 
This addressed AC#1, AC#2 for 491. Using the database, we can configure:
- Filenames in a more fine-grained way, so that if, for example, a program requires two different TDI17s, we can account for that
- Alerts in a more fine-grained way, so that we can configure who gets what email

[CCFPCM-491] required files, alert destinations

---

.husky/pre-commit
package.json
yarn.lock

Objective: 
- pre-commit hook was not running (runs lint-staged on commit)
- to enable, run `yarn` followed by `yarn husky install` 
- pre-commit hook can be overridden by using the `-n` flag when committing 
example console printout:

[CHORE] fix pre-commit hook

---

apps/backend/fixtures/lambda/reconcile.json
apps/backend/src/lambdas/reconcile.ts
apps/backend/src/reconciliation/cash-exceptions.service.ts
apps/backend/src/reconciliation/cash-reconciliation.service.ts
apps/backend/src/reconciliation/types/interface.ts
apps/backend/src/reporting/interfaces.ts

[CCFPCM-0575](https://bcdevex.atlassian.net/browse/CCFPCM-0575)
Objective: 
- Reconciliation Lambda to trigger report output
- TODO: set the daily file check lambda to trigger the reconciliation once daily per LoB (if all files present, otherwise, alert)
- TODO: move this outside of the lambda function and use the destination to trigger the lambda instead
- **note:** the reconciled on, in progress on, and uploaded on dates are still a bit messed up. We will need to use only the realtime dates once automation is in place, but if we run a batch reconciliation for a specific date and then try to generate the report it will break, as the report will include all items reconciled on that date (so if you reconcile the entire dataset in one go you will be generating a report for the full dataset)

[CCFPCM-0575] reconciliation to trigger report

---

apps/backend/src/deposits/pos-deposit.service.ts

[CCFPCM-565](https://bcdevex.atlassian.net/browse/CCFPCM-565)
Objective: 
The left join on the payment method was adding more rows than necessary because it was left-joining the 1:X relationships on the entity. This PR makes it closer to Karim's query

[CCFPCM-565] fix pos amounts for reports page 3

---

terraform/bastion.tf

[CCFPCM-577](https://bcdevex.atlassian.net/browse/CCFPCM-577)
Objective: 
- Addresses the high sev alert in Security Hub
- Must specify this metadata to limit IMDS to only support v2, not also v1 (default setting allows both)
- Note I haven't applied this change yet :) I decided it would be best to keep scope small for this fix, but open to hearing we should address other things as part of this same PR

[CCFPCM-577] Require IMDSv2 for bastion host config

---

Makefile
apps/backend/README.md
apps/backend/fixtures/lambda/batch.json
apps/backend/fixtures/lambda/reconcile.json
apps/backend/fixtures/lambda/report.json
apps/backend/src/lambdas/batch-reconcile.ts
apps/backend/src/lambdas/batch-run.ts
apps/backend/src/lambdas/const.ts
apps/backend/src/lambdas/helpers.ts
apps/backend/src/lambdas/interface.ts
apps/backend/src/lambdas/parser.ts
apps/backend/src/lambdas/reconcile.ts
apps/backend/src/lambdas/report.ts
apps/backend/src/parse/parse.module.ts
apps/backend/src/parse/parse.service.ts
apps/backend/src/reconciliation/cash-reconciliation.service.ts
apps/backend/src/reporting/interfaces.ts
apps/backend/src/reporting/reporting.service.ts
apps/backend/test/unit/parsing/parse-service.spec.ts
terraform/lambda_batch_reconciler.tf
terraform/lambda_dailyfilecheck.tf
terraform/lambda_parser.tf
terraform/lambda_reconciler.tf
terraform/lambda_reporting.tf
terraform/sns.tf
terraform/variables.tf

[CCFPCM-610](https://bcdevex.atlassian.net/browse/CCFPCM-610)
In order to run the reconciliation on the entire dataset as though it had run daily we should use the file metadata and filename (for SBC json files) to extract the date and run reconciliation based on that date. 
**How To Run On local:**
- Parsing, reconciliation and reports are now all automated by default. When you run sync/parse the entire dataset will be reconciled (job is >1 hr but should only need to run once per env unless you drop your db)
- to test: ‘make drop', ‘make migrations-run’, ‘make sync’, 'make parse’ 
- Reconciliation can be run manually (only runs for the specified dates, does not batch):
- 'make reconcile' and update reconcile.json
- Automated reconciliation can be turned off:
- set …

[CCFPCM-610] batch-reconciliation

---

terraform/bastion.tf

Objective: 
- Resolve the error below
- [terraform-provider-aws reference](https://github.com/hashicorp/terraform-provider-aws/issues/22465)
```
│ Error: creating EC2 Instance: InvalidParameterValue: A value of '' is not valid for HttpEndpoint. Specify either 'enabled' or 'disabled' and try again.
│       status code: 400, request id: 6bd7d5ab-f87b-4b94-ac19-a3dafee6cd86
│ 
│   with aws_instance.bastion_instance,
│   on bastion.tf line 69, in resource "aws_instance" "bastion_instance":
│   69: resource "aws_instance" "bastion_instance" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
make: *** [apply] Error 1
```

[FIX] bastion metadata_options error

---

apps/backend/webpack.config.js

Objective: 
- added api lambda to webpack config
** note: this does not resolve the issue entirely as we are not building the swagger UI, but the endpoint is returning a 200 so this  is a partial fix

[FIX] api lambda added to webpack

---

apps/backend/src/database/migrations/1692293473030-migration.ts
apps/backend/src/lambdas/dailyfilecheck.ts
apps/backend/src/notification/entities/file-ingestion-rules.entity.ts
apps/backend/src/notification/entities/program-daily-upload.entity.ts
apps/backend/src/notification/notification.service.ts
apps/backend/src/parse/parse.controller.ts
apps/backend/src/parse/parse.service.ts
apps/backend/test/mocks/classes/file_ingestion_rules_mock.ts
terraform/lambda_dailyfilecheck.tf

[CCFPCM-570](https://bcdevex.atlassian.net/browse/CCFPCM-570)
[CCFPCM-612](https://bcdevex.atlassian.net/browse/CCFPCM-612)
Objective: 
- Automate alerts with a cron job using cloudwatch events at 11, 14, 17 (this may need to be adjusted depending on timezone)
- Only alert if files have been sent in across any LOB for the day
- We stop sending alerts if a daily upload was incomplete 7+ days ago. We can remove this logic; I just figure at that point, if files have continued to be uploaded, we can reconcile?
- Remove concept of "retries" as it's now in set times

[CCFPCM-570] cron job for daily file check alerting

---

terraform/lambda_dailyfilecheck.tf

[CCFPCM-570](https://bcdevex.atlassian.net/browse/CCFPCM-570)
Objective: 
I noted that the times in the scheduled expression are utc, so I adjusted accordingly. I also found that AWS cron needs 6 stars (the question mark here being for 'day of week').

[CCFPCM-570] change to utc, proper cron expression (specialied AWS cron)

---

terraform/budget.tf

[CCFPCM-606](https://bcdevex.atlassian.net/browse/CCFPCM-606)
Objective: 
Added alert sent to provided email address when exceeding monthly target budget per environment.
Sample of what this notification will look like (note: amounts in this preview are not accurate, as they were just set to make sure the emails would trigger)

[CCFPCM-606] Added budget + alerts when exceeding target

---

terraform/db.tf

[CCFPCM-597](https://bcdevex.atlassian.net/browse/CCFPCM-597)
Objective: 
Enabled export of postgres logs to CloudWatch in order to resolve the "Enable additional RDS logging" Security Hub alert. This will create a CloudWatch log group called `/aws/rds/cluster/{db cluster name}/postgresql` where the logs can be found.
This may or may not be sufficient to resolve CCFPCM-407 - AC 2: Ability send reports of access to Auditors, depending on the verbosity of these logs. Will verify once deployed

[CCFPCM-597] Enabled RDS logging + export to Cloudwatch

---

apps/backend/src/lambdas/dailyfilecheck.ts
apps/backend/src/lambdas/parser.ts
apps/backend/src/notification/entities/alert-destination.entity.ts
apps/backend/src/notification/mail.service.ts

[CCFPCM-570](https://bcdevex.atlassian.net/browse/CCFPCM-570)
[CCFPCM-630](https://bcdevex.atlassian.net/browse/CCFPCM-630)
[CCFPCM-631(https://bcdevex.atlassian.net/browse/CCFPCM-631)
Objective: 
Using the earliest status could miss a lot of the issues in between, so we are now alerting for all the daily issues. Change in logic to email all / rule destinations a summary, and file destinations a single email per file

[CCFPCM-630] alert for all unsuccessful statuses in past 7 days

---

.github/workflows/deploy-prod.yaml

Objective: 
Point the prod deployment workflow to the new ENV which requires approvals.
NOTE: The new ENV has been tested by a branch that points the S3 sync to it. I was prompted to approve, and we can see from this screenshot that the AWS creds are correct, and that the error it throws is the same as the usual errors (single file issue)

[CHORE] point prod deployment to new github env

---

terraform/db.tf

[CCFPCM-407](https://bcdevex.atlassian.net/browse/CCFPCM-407)
Objective: 
- Disabled DB backups in dev environment
- Increased DB backup retention period in test environment to match production (14 days). This will also resolve the DB backup not enabled alert in security hub which required a minimum 7 day retention period.

[CCFPCM-407] Disabled rds backups in dev, increased retention period in test to match prod

---

apps/backend/src/database/datasource.ts

[CCFPCM-602](https://bcdevex.atlassian.net/browse/CCFPCM-602)
Objective: 
Fixes DB migrations when running the migrator lambda. New migrations are currently not being picked up by typeorm when running the Migrator lambda. Typeorm can't find any migrations to run in the `/migrations` folder seeing as Webpack bundles them together with the app.
Solution:
Dynamically load migrations using webpack contexts, which will let us keep a reference to the migrations after the app has been built. When running it locally, it will still use the glob pattern to look up the migrations, as it's not using webpack at that time.

[CCFPCM-602] Fixed db migrations not running in dev

---

terraform/db.tf
terraform/main.tf

[CCFPCM-407](https://bcdevex.atlassian.net/browse/CCFPCM-407)
Objective: 
- Enabled the `pgaudit` postgres extension to capture DB audit logs to meet audit and reporting requirements.
- Audit logs is output to the `aws/rds/cluster/pcc-db/postgresql` CloudWatch group
- pgAudit has been configured to log "ALL" statements, this can be tweaked in the new RDS parameter group created in this PR. Available options can be found here: https://access.crunchydata.com/documentation/pgaudit/latest/#settings
Changes:
- Enables `pgaudit` extension
- Creates new `rds_pgaudit` db role for use by pgaudit
- Creates new RDS Param group `pgsql-audit-param-group` to configure pgaudit

[CCFPCM-407] Enabled RDS pgAudit extension

---

terraform/s3.tf
terraform/sftp.tf

[CCFPCM-407](https://bcdevex.atlassian.net/browse/CCFPCM-407)
Objective: 
- Enabled s3 access logging (https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html)
Changes:
- Created new s3 bucket for storing S3 access logs (`pcc-s3-access-logs-${var.target_env}`)
- Enabled access logging on existing s3 buckets

[CCFPCM-407] Enabled s3 access logging

---

terraform/db.tf

[CCFPCM-595](https://bcdevex.atlassian.net/browse/CCFPCM-595)
Objective: 
Turns out you cannot actually disable backups on Aurora DBs, so set the backup retention period to a minimum of 1 day for the dev environment.

[CCFPCM-595] Re-enable backups of dev db

---

.github/workflows/ci-tests.yaml
Makefile

Objective: 
- we need to call the migrate lambda in order for the seed data to run
- I have updated the Makefile cmd to trigger the migrations from the lambda instead of the typeorm cli

[FIX] local migrations/seed data

---

terraform/s3.tf

[CCFPCM-590](https://bcdevex.atlassian.net/browse/CCFPCM-590)
Objective: 
Added missing ACL to S3 access log bucket. It needs the `log-delivery-write` acl in order to receive access logs from the other buckets

[CCFPCM-590] Added missing s3 access log permission to bucket

---

Makefile
apps/backend/src/database/migrate.ts

Should address [CCFPCM-630](https://bcdevex.atlassian.net/browse/CCFPCM-630)
Objective: 
Noticed that the migrator logic created both locations and rules twice. This should take care of that

[FIX] remove handler() call from migrator lambda

---

apps/backend/fixtures/lambda/reconcile.json
apps/backend/src/lambdas/reconcile.ts

Objective: 
- file check date should be minus one business day

[FIX] reconciliation filecheck date

---

terraform/local.tf
terraform/s3.tf

[CCFPCM-589](https://bcdevex.atlassian.net/browse/CCFPCM-589)
Objective: 
- Enabled SSL enforcement on all S3 buckets
- Added policies to block public ACLs to all S3 buckets.

[CCFPCM-589] Force SSL traffic to S3 buckets + block public ACLs

---

apps/backend/src/constants.ts
apps/backend/src/parse/parse.controller.ts

[CCFPCM-0000](https://bcdevex.atlassian.net/browse/CCFPCM-627)
Objective: 
Limit file extensions coming in on the API endpoint

[CCFPCM-672] add errors to limit file extensions

---

Makefile
bin/sync.sh

[CCFPCM-0679](https://bcdevex.atlassian.net/browse/CCFPCM-0679)
Objective: 
- The data bucket has too many items to list in a single call when manually parsing. This does not affected automated parsing as we are simply parsing the files dropped in through the automation flow, vs comparing the filelist from s3 with the db file upload table. 
- remove archive from dev/local and do not sync the archive folder

[CCFPCM-0679] Bugfix for manual parsing 

---

terraform/api.tf
terraform/s3.tf

Objective: 
- Fix runtime env variable for the lambda api (required for uploading files to the bucket)
- Fix the public acl block on reporting bucket (I noticed that it had changed during a terraform plan - I think this was leftover from updating the prod infra/migrating the terraform backend)
- Tried to increase the request limit on the api but still getting an error for large files

[FIX] Runtime env in terraform + block public acls on report bucket

---

apps/backend/src/database/migrations/1698765712684-location-migration.ts
apps/backend/src/location/entities/bank.entity.ts
apps/backend/src/location/location.service.ts

[CCFPCM-0426](https://bcdevex.atlassian.net/browse/CCFPCM-0426)
Objective: 
- Since the migrations have not yet been deployed I am adding the method to the bank_id table (to use in testing and for easy reference)

[CCFPCM-426] PT 1.1 -  added method to bank table
