bcgov/PaymentCommonComponent

apps/backend/src/lambdas/generateData.ts, apps/backend/src/lambdas/utils/parseGarms.ts, apps/backend/src/logger/format.ts, apps/backend/src/transaction/interface/sbc_garms.ts, apps/backend/src/transaction/interface/transaction.interface.ts, apps/backend/src/transaction/transaction.controller.ts
[FIX](https://bcdevex.atlassian.net/browse/CCFPCM-0311)
Objective: 
Fixed name on SBCGarmsJson (from SBCGarmsJsonJson)
Added TODO for saving json from api
Changed 'info' to 'INFO' on the logger label
=> [FIX]: garms json name

apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/reconciliation/cash-reconciliation.service.ts, apps/backend/src/transaction/entities/payment.entity.ts, apps/backend/src/transaction/payment.service.ts
[CCFPCM-0362](https://bcdevex.atlassian.net/browse/CCFPCM-0362)
Fix error on cash match check - (setting entire array to match due to typo in "if" statement)
Update logs
=> [CCFPCM-0362/bugfix] Cash Match

apps/backend/src/database/migrations/1677775665682-migration.ts, apps/backend/src/lambdas/utils/parseGarms.ts, apps/backend/src/transaction/payment.service.ts
[CCFPCM-0000](https://bcdevex.atlassian.net/browse/CCFPCM-0000)
Objective: 
- Filter out zero dollar amount when parsing garms SBC files
- Update cash payments query
- Write migration to remove current zero dollar amount payments from the db
=> [FIX] filtering zero amount in parse garms

apps/backend/src/database/migrations/1677790299143-migration.ts, apps/backend/src/deposits/entities/pos-deposit.entity.ts
[FIX](https://bcdevex.atlassian.net/browse/CCFPCM-0000)
- remove "match" column from pos_deposit
=> [FIX] drop match column pos_deposit

apps/backend/src/common/entities/FixedWidthRecord.ts, apps/backend/src/common/utils/formatFixedWidth.ts, apps/backend/src/database/migrations/1677866567491-migration.ts
[CCFPCM-0337](https://bcdevex.atlassian.net/browse/CCFPCM-0337)
Deposi date column fix
=> [CCFPCM-0337]  deposit date column for cash deposit

apps/backend/fixtures/lambda/reconcile.json, apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/location/location.service.ts, apps/backend/src/reconciliation/cash-reconciliation.service.ts, apps/backend/src/reconciliation/types/interface.ts, apps/backend/src/reporting/reporting.service.ts, apps/backend/src/transaction/payment.service.ts, apps/backend/src/transaction/transaction.module.ts, apps/backend/src/transaction/transaction.service.ts
[CHORE](https://bcdevex.atlassian.net/browse/CCFPCM-0000)
Clean up the current cash match. Match only one deposit date per date per location. 
Improve logging.
New output (Deposit ID can be used to query the matching payments for testing):
=> [CHORE] update logging and improve cash match

apps/backend/src/common/promises.ts, apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/lambdas/parser.ts, apps/backend/src/transaction/transaction.service.ts
[CCFPCM-417](https://bcdevex.atlassian.net/browse/CCFPCM-417)
=> [CCFPCM-417] implement map limit for parsing

.gitignore, docs/reconciliation.readme.md
Objective: 
Update reconciliation readme
=> [CHORE] updated reconciliation readme

apps/backend/fixtures/lambda/reconcile.json, apps/backend/fixtures/lambda/report.json, apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/logger/logger.service.ts, apps/backend/src/reconciliation/cash-reconciliation.service.ts, apps/backend/src/reconciliation/pos-reconciliation.service.ts, apps/backend/src/reporting/detailed-report/cash-details-report.ts, apps/backend/src/reporting/detailed-report/details-report.ts, apps/backend/src/reporting/detailed-report/payment-details-report.ts, apps/backend/src/reporting/detailed-report/pos-details-report.ts, apps/backend/src/reporting/details-report.service.ts, apps/backend/src/reporting/reporting.module.ts, apps/backend/src/reporting/reporting.service.ts, apps/backend/src/transaction/payment.service.ts, apps/backend/test/deposits/cash-deposit.service.spec.ts, apps/backend/test/reporting/reporting.service.spec.ts
[CCFPCM-465](https://bcdevex.atlassian.net/browse/CCFPCM-465)
Objective: 
- rename some items
- review reconciliation functions to find why some are not being set to exceptions
- code clean up 
- - split details report into a separate service
=> [CCFPCM-465] IN_PROGRESS -> EXCEPTIONS (cash)

.github/workflows/pr.yaml
Objective: 
- adding a manual trigger for PR checks...
=> [CHORE]: manual trigger for all PR checks workflow

apps/backend/src/reconciliation/cash-reconciliation.service.ts, apps/backend/src/reconciliation/pos-reconciliation.service.ts, apps/backend/src/reconciliation/types/interface.ts, apps/backend/src/transaction/entities/payment.entity.ts, apps/backend/src/transaction/payment.service.ts, apps/backend/test/mocks/classes/cash_deposit_mock.ts, apps/backend/test/mocks/mocks.cash.spec.ts, apps/backend/test/mocks/mocks.ts, apps/backend/test/unit/deposits/cash-deposit.service.spec.ts, apps/backend/test/unit/reconciliation/cash-reconciliation.spec.ts, apps/backend/test/unit/reconciliation/helpers.ts, apps/backend/test/unit/reconciliation/pos-reconciliation.spec.ts
Objective: 
- fixed empty test data in unit tests
- please see the cash reconciliation updates (had an error in this file)
=> [CHORE] update unit tests - fix test matches

.gitignore, Makefile, apps/backend/fixtures/lambda/reconcile.json, apps/backend/fixtures/lambda/report.json, apps/backend/src/constants.ts, apps/backend/src/database/migrations/1685550790907-migration.ts, apps/backend/src/deposits/entities/pos-deposit.entity.ts, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/reconciliation/pos-reconciliation.service.ts, apps/backend/src/reporting/reporting.service.ts, apps/backend/src/transaction/entities/payment.entity.ts, apps/backend/src/transaction/payment.service.ts, docker-compose.ci.yml
[CCFPCM-0498](https://bcdevex.atlassian.net/browse/CCFPCM-0498)
Objective: 
- heuristic round for pos recon
- update reports
=> [CCFPCM-498] heuristic 4 + report updates

.sonarcloud.properties
[CCFPCM-518](https://bcdevex.atlassian.net/browse/CCFPCM-518)
Objective: 
- Add the properties file as a prerequisite to further SQ config
=> [CCFPCM-515] (subtask 518): Added basic SQ properties file

apps/backend/test/unit/reconciliation/pos-reconciliation.spec.ts
Objective: 
- unit test round four
=> [CHORE] unit tests heuristic four

apps/backend/fixtures/lambda/reconcile.json, apps/backend/fixtures/lambda/report.json, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/lambdas/report.ts, apps/backend/src/transaction/payment.service.ts
Objective: 
- remove duplicate MATCH from report
=> [FIX] report duplicates

apps/backend/fixtures/lambda/report.json, apps/backend/src/reporting/const.ts, apps/backend/src/reporting/detailed-report/payment-details-report.ts, apps/backend/src/reporting/interfaces.ts, apps/backend/src/reporting/reporting.service.ts
[CCFPCM-0502](https://bcdevex.atlassian.net/browse/CCFPCM-0502)
Objective: 
- include the same info for deposits as we have for payments on the summary page
=> [CCFPCM-502]: Summary Page Deposit Info

.config/.env.example, README.md
=> [CHORE] update .env.example

apps/backend/src/lambdas/parser.ts, apps/backend/src/lambdas/utils/parseGarms.ts, apps/backend/src/parse/dto/garms-transaction.dto.ts, apps/backend/src/parse/entities/file-uploaded.entity.ts, apps/backend/src/parse/parse.service.ts
[CCFPCM-502](https://bcdevex.atlassian.net/browse/CCFPCM-502)
Objective: 
- Remove errant commenting out of process event
- Check proper uploaded filenames rather than the ones in the various tables
- Remove validation for total payments for now; see [CCFPCM-534](https://bcdevex.atlassian.net/browse/CCFPCM-534)
- Revert logic for rounding exchange rate
- Surface validation errors better
=> [CCFPCM-502] Fixing some issues

apps/backend/src/deposits/entities/pos-deposit.entity.ts, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/transaction/entities/payment.entity.ts, apps/backend/src/transaction/payment.service.ts
=> [FIX] payment_match.id rename

apps/backend/src/flat-files/tdi17/TDI17Details.ts, apps/backend/src/flat-files/tdi34/TDI34Details.ts, apps/backend/src/parse/dto/cash-deposit.dto.ts, apps/backend/src/parse/dto/pos-deposit.dto.ts
Objective: 
By changing from decimal to float, it was missing adding the right decimal place.
Reverted that, and made the dto IsNumberString for now
=> [FIX] fix deposits coming in as decimals

apps/backend/src/flat-files/tdi17/TDI17Details.ts, apps/backend/src/flat-files/tdi34/TDI34Details.ts, apps/backend/src/parse/dto/cash-deposit.dto.ts, apps/backend/src/parse/dto/pos-deposit.dto.ts
=> [FIX] ensure numerical value in tdi details, revert dto to isnumber

apps/backend/src/lambdas/parser.ts
Objective: The API gateway on the api lambda doesn't seem able to take requests from the parser lambda, so this is an interim workaround.
=> [CHORE] parser axios issues

apps/backend/src/flat-files/tdi17/TDI17Details.ts, apps/backend/src/parse/dto/cash-deposit.dto.ts
=> [FIX] fix decimal for tdi17

apps/backend/fixtures/lambda/reconcile.json, apps/backend/fixtures/lambda/report.json, apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/lambdas/report.ts, apps/backend/src/reconciliation/cash-reconciliation.service.ts, apps/backend/src/reporting/const.ts, apps/backend/src/reporting/interfaces.ts, apps/backend/src/reporting/reporting.service.ts, apps/backend/src/transaction/payment.service.ts, apps/backend/test/unit/deposits/cash-deposit.service.spec.ts
[CCFPCM-0509](https://bcdevex.atlassian.net/browse/CCFPCM-0509)
Objective: 
- Generate reports based on the provided "from" and "to" dates in the report.json file.
- Set report gen limit to 15 days
- If we span across two months, page three CAS report will include the full month from the to-date as well as any dates up  to the "from date" of the next month. 
[report.xlsx](https://github.com/bcgov/PaymentCommonComponent/files/11776755/report.xlsx)
=> [CCFPCM-509] Multiple date report

Makefile
Objective: 
- rename the clear-status cmd 
- add a clear-database cmd
=> [CHORE] Makefile

apps/backend/fixtures/lambda/reconcile.json, apps/backend/fixtures/lambda/report.json, apps/backend/src/excelexport/excelexport.service.ts, apps/backend/src/lambdas/report.ts, apps/backend/src/reporting/reporting.service.ts
[CCFPCM-544](https://bcdevex.atlassian.net/browse/CCFPCM-544)
Objective: 
- When generating reports larger than a few days or weeks we are getting a JavaScript Heap out of memory error
- To resolve we are using a workbook stream so that the entire workbook does not need to be saved in memory prior to writing to a file
*note: deployed to test and verified upload (have since reverted test to main branch since this is not yet through PR)
=> [CCFPCM-544] fix heap memory error for reports

.github/workflows/ci-jira.yaml, .github/workflows/ci-lint.yaml, .github/workflows/ci-tests.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/deploy-zap-dev.yaml, .github/workflows/s3-files-sync.yaml, package.json
[CCFPCM-522](https://bcdevex.atlassian.net/browse/CCFPCM-522)
Objective: 
- Applied consistency updates across the workflows
- Updated actions versions where applicable
- Locked Node at v18 in package.json to align with test workflow and terraform env (to be upgraded later since it's in LTS as of Feb, just aiming for predictability right now)
- Removed the param to prevent ZAP issue writing (docs were wrong? It expects different input however I can't find a counterexample to how I attempted to use it, which is following the docs, and I don't feel strongly about issue writing so I didn't invest more time investigating)
- Renamed the sync job to be clear it ONLY syncs files between S3 buckets, it does not parse or sync data
=> [CCFPCM-522] Consistency updates for workflows and Node version, updated file sync naming

apps/backend/src/lambdas/reconcile.ts
[CCFPCM-525](https://bcdevex.atlassian.net/browse/CCFPCM-525)
Objective: 
Just an error message change
=> [FIX] error message for preventing reconciler

apps/backend/src/lambdas/parser.ts, apps/backend/src/parse/parse.controller.ts, apps/backend/src/parse/parse.service.ts, apps/backend/test/unit/parsing/parse-service.spec.ts
[CCFPCM-479](https://bcdevex.atlassian.net/browse/CCFPCM-479)
Objective: 
This will show us which files are missing
=> [FIX] Identify missing files in logs

.github/workflows/clear-all-data-dev.yaml, .github/workflows/reset-transaction-status-dev.yaml, Makefile
[CCFPCM-519](https://bcdevex.atlassian.net/browse/CCFPCM-519)
Objective: 
- Added two jobs, one that resets status and one that clears all key data (DB and S3)
- The new Makefile command for the S3 buckets is targeting subfolders
- I'll need to run these to confirm they work in GHA env (I believe the necessary connection vars are already available to the make commands - but need to confirm) - got the all-clear from Qudsia already to wipe dev DB as needed for testing
- We also have the option to configure approvers for these workflows in GH if we want to
=> [CCFPCM-519] Clear DB data and S3 jobs

Makefile
Objective: 
- The makefile and the workflow got out of sync (ha) somehow, quick fix
=> [FIX] Fixed typo in makefile command

apps/backend/fixtures/lambda/report.json, apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/transaction/payment.service.ts
Objective: 
- removed method to mutate the dates array and am instead getting the correct order in the query
=> [FIX] cash date

apps/backend/fixtures/lambda/reconcile.json, apps/backend/fixtures/lambda/report.json, apps/backend/src/reporting/reporting.service.ts
Objective: 
- remove filter duplicates, some duplicates should be expected
=> [FIX] remove report duplicates filter

apps/backend/fixtures/lambda/report.json, apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/excelexport/excelexport.service.ts, apps/backend/src/lambdas/report.ts, apps/backend/src/reporting/cas-report/cas-report.ts, apps/backend/src/reporting/const.ts, apps/backend/src/reporting/detailed-report/cash-details-report.ts, apps/backend/src/reporting/detailed-report/details-report.ts, apps/backend/src/reporting/detailed-report/payment-details-report.ts, apps/backend/src/reporting/detailed-report/pos-details-report.ts, apps/backend/src/reporting/reporting.service.ts, apps/backend/src/transaction/payment.service.ts
[CCFPCM-0561](https://bcdevex.atlassian.net/browse/CCFPCM-0561)
[CCFPCM-0564](https://bcdevex.atlassian.net/browse/CCFPCM-0564)
Objective: 
- Bug fix: remove duplicate PENDING txns (add payment classification to the PENDING payments to avoid duplicates)
- Updates (to ease testing): 
- expand the reconciled_on query date filter to +- 2 business days
- Add UUID and match ID as hidden columns
- Change all dates to type of date
- format the dates automatically using the numFmt in the cell.style property
- remove title row
=> [CCFPCM-0561] FIX - Duplicates/[CCFPCM-564] Report Updates

.github/workflows/s3-files-sync-dev-manual.yaml
Objective: 
- adding a manual trigger to sync files to dev to test the automated parsing
=> [CHORE] test s3 sync and parse

apps/backend/src/lambdas/dailyfilecheck.ts, apps/backend/src/notification/mail-templates.ts, apps/backend/src/notification/mail.service.ts, apps/backend/src/notification/notification.service.ts, apps/backend/src/parse/parse.service.ts
[CCFPCM-491](https://bcdevex.atlassian.net/browse/CCFPCM-491)
Objective: 
Use the new templates for the alerts, including new fields for them
=> [CCFPCM-491] use new, styled templates for alerts

Makefile, apps/backend/src/database/const.ts, terraform/lambda_dailyfilecheck.tf, terraform/s3.tf
Objective: 
- make bucket name unique across envs
=> [FIX] fix bucketname

Makefile
Objective: 
- fix deployment for the new lambdas
=> [FIX] deploy changes to the lambdas

Makefile
Objective: 
- fix bucket name for local master data
=> [FIX] fix bucket name for local static data

Makefile, apps/backend/src/lambdas/const.ts, apps/backend/src/lambdas/dailyfilecheck.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/notification/mail.service.ts, apps/backend/src/notification/notification.service.ts, apps/backend/src/parse/parse.service.ts, apps/backend/src/parse/ro/daily-alert.ro.ts, apps/backend/test/unit/parsing/parse-service.spec.ts
[CCFPCM-0600](https://bcdevex.atlassian.net/browse/CCFPCM-0600)
Objective: 
- add types wherever possible and rename some functions for readability
- address complexity warning for parse service fnc from sonarqube
- Update email template for daily alert
=> [CCFPCM-600] email alert templates + renaming fncs

.config/.env.example, Makefile, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/lambdas/report.ts, terraform/lambda_batch_reconciler.tf, terraform/lambda_parser.tf, terraform/lambda_reconciler.tf, terraform/lambda_reporting.tf, terraform/sns.tf, terraform/variables.tf
Objective: 
- ensure reports are being generated to S3 bucket
=> [FIX] report lambda

apps/backend/src/lambdas/const.ts, apps/backend/src/notification/notification.service.ts
Objective: 
- apostrophe missing
=> [FIX] email template - missing apostrophe

.config/.env.example, apps/backend/fixtures/lambda/batch.json, apps/backend/fixtures/lambda/reconcile.json, apps/backend/src/lambdas/batch-reconcile.ts, apps/backend/src/lambdas/interface.ts, apps/backend/src/lambdas/parser.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/parse/parse.service.ts, terraform/lambda_parser.tf, yarn.lock
Objective: 
- use current date in both prod/test
- use inferred date if running the batch reconciliation, or on dev/local
=> [CHORE] Use current date in prod/test

apps/backend/src/lambdas/dailyfilecheck.ts
[CCFPCM-570](https://bcdevex.atlassian.net/browse/CCFPCM-570)
Objective: 
Files are uploaded for the day before, so `dailyDate` comes the day after. We use `created_at` instead, though SBC files get uploaded in the night (11pm PST on 2023-08-22 for the 2023-08-22 file for example), in UTC the created_at should be fine (it'll show as 2023-08-23).
=> [CCFPCM-570] check upload date rather than daily date

terraform/lambda_dailyfilecheck.tf
[CCFPCM-520](https://bcdevex.atlassian.net/browse/CCFPCM-520)
Objective:
=> [FIX] change cron from 5pm to 4pm

apps/backend/package.json, apps/backend/webpack.config.js, yarn.lock
[CCFPCM-0616](https://bcdevex.atlassian.net/browse/CCFPCM-0616)
Objective: 
- ensure swagger UI builds with webpack
=> [CCFPCM-0616] swagger ui in webpack

apps/backend/src/parse/parse.service.ts
[CCFPCM-620](https://bcdevex.atlassian.net/browse/CCFPCM-620)
Objective:
=> [FIX] change metadata date to to date for tdi 17

terraform/api.tf, terraform/lambda_batch_reconciler.tf, terraform/lambda_dailyfilecheck.tf, terraform/lambda_migrator.tf, terraform/lambda_parser.tf, terraform/lambda_reconciler.tf, terraform/lambda_reporting.tf
=> [FIX] app version

terraform/db.tf
[CCFPCM-663](https://bcdevex.atlassian.net/browse/CCFPCM-663)
Objective: 
- Downsized RDS DB size from `t3.large` to `t3.medium` in order to reduce costs.
=> [CCFPCM-663] Downsize RDS to t3.medium

terraform/sftp.tf
[CCFPCM-634 ](https://bcdevex.atlassian.net/browse/CCFPCM-634)
Objective: 
- Removed SFTP transfer family resources from dev and test environment to reduce costs.
- This includes: aws_transfer_server, aws_transfer_user  and aws_transfer_ssh_key resources
TF Plan:
```
- resource "aws_transfer_server" "sftp" {
- arn                              = "arn:aws:transfer:ca-central-1:279397349124:server/s-1a6fff3badeb4aa7a" -> null
- domain                           = "S3" -> null
- endpoint                         = "s-1a6fff3badeb4aa7a.server.transfer.ca-central-1.amazonaws.com" -> null
- endpoint_type                    = "PUBLIC" -> null
- force_destroy                    = false -> null
- host_key_fingerprint             = "SHA256:PxSG5iTBwRnY1DISeclsDRM9yWMnacyDJHsojbGRjEI=" -> null
- id …
```
=> [CCFPCM-634] Removed SFTP Transfer family services from dev/test

apps/backend/src/lambdas/utils/parseGarms.ts, apps/backend/src/lambdas/utils/parseTDI.ts, apps/backend/src/logger/logger.service.ts, apps/backend/src/notification/notification.service.ts, apps/backend/src/parse/parse.service.ts, apps/backend/src/s3-manager/s3-manager.service.ts
[CCFPCM-0660](https://bcdevex.atlassian.net/browse/CCFPCM-0660)
Objective: 
- flattened out some of the parse service methods to ensure that nested try/catches do not generate messages to be sent in emails
- Updated the generic message sent to users
=> [CCFPCM-0660] bugfix for email for generic errors

.github/workflows/clear-all-data-dev.yaml, .github/workflows/deploy-zap-dev.yaml, Makefile, apps/backend/src/database/clear-dev-db.ts, terraform/clear-dev-db.tf
[CCFPCM-0571](https://bcdevex.atlassian.net/browse/CCFPCM-0571)
Create a Lambda function for development environment, set up a GitHub Action to invoke the Lambda and clear the dev database, update Terraform for Lambda deployment, and implement environment checks within the Lambda function to restrict script execution to dev or local environments.
**Tasks:**
- Create Lambda Function to clear the development database.
- Implement environment checks within the Lambda to ensure that the script execution is restricted to the development (dev) or local environments.
- GitHub Action Setup:
- Configure a GitHub Action workflow that invokes the Lambda function to clear the dev database.
This should have a manual trigger
- Terraform Update:
- Modify our Terraform configuration to …
=> [CCFPCM-0571] Job to wipe dev db

Makefile, apps/backend/webpack.config.js
[CCFPCM-0666](https://bcdevex.atlassian.net/browse/CCFPCM-0666)
Objective: 
- Updated webpack config to include the wipe dev db lambda
=> [CCFPCM-666] Updated webpack for the wipe db lambda

Makefile, terraform/s3.tf, terraform/sftp.tf
[CCFPCM-0667](https://bcdevex.atlassian.net/browse/CCFPCM-0667)
Objective: 
- update bucket policies for pcc-data-files to allow for sync to run
=> [CCFPCM-0667] sync job 

Makefile, terraform/bastion.tf, terraform/budget.tf, terraform/clear-dev-db.tf, terraform/db.tf, terraform/lambda_batch_reconciler.tf, terraform/lambda_dailyfilecheck.tf, terraform/lambda_migrator.tf, terraform/lambda_parser.tf, terraform/local.tf, terraform/s3.tf, terraform/sftp.tf, terraform/sns.tf
Objective: 
- run terraform fmt
- include fmt in makefile cmds
=> [CHORE] TF format (whitespace changes only)

Makefile
Objective: 
- sync to TEST not dev
=> [FIX] test files sync

apps/backend/fixtures/lambda/reconcile.json, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/lambdas/reconcile.ts, apps/backend/src/reconciliation/ministryHeuristics.ts, apps/backend/src/reconciliation/pos-reconciliation.service.ts, apps/backend/src/reconciliation/types/interface.ts, apps/backend/src/reporting/reporting.service.ts, apps/backend/src/transaction/payment.service.ts, apps/backend/test/unit/deposits/pos_deposit.service.spec.ts, apps/backend/test/unit/reconciliation/pos-reconciliation.spec.ts, docs/reconciliation.md
[CCFPCM-643](https://bcdevex.atlassian.net/browse/CCFPCM-643)
Objective: 
- refactor for: SQ cognitive complexity for pos reconciliation service
=> [CCFPCM-643] pos refactor for SQ warning

apps/backend/src/lambdas/reconcile.ts, terraform/lambda_reporting.tf
Objective: 
- memory limit error on report lambda resolved
=> [FIX] report lamba memory issue - V1.0.0

apps/backend/src/lambdas/reconcile.ts, terraform/lambda_reporting.tf
=> [FIX] report lamba memory issue

apps/backend/src/lambdas/reconcile.ts, terraform/lambda_reporting.tf
=> [FIX] report lamba memory issue (#259)

Makefile, terraform/s3.tf
=> [FIX] PROD tf changes

.github/workflows/deploy-prod.yaml, Makefile
Objective: 
- FIX deploy command in prod gh actions
=> [FIX] deploy cmd

.github/workflows/deploy-prod.yaml, Makefile, apps/backend/src/lambdas/reconcile.ts, terraform/lambda_reporting.tf, terraform/s3.tf
Objective: 
- resolve lambda memory error (for main branch)
=> [FIX] report lamba memory issue - MAIN

apps/backend/src/constants.ts, apps/backend/src/parse/parse.controller.ts, apps/backend/src/parse/parse.module.ts, apps/backend/src/parse/upload.service.ts, apps/backend/src/s3-manager/s3-manager.service.ts
[CCFPCM-654](https://bcdevex.atlassian.net/browse/CCFPCM-654)
Objective: 
- Fix file upload end point
- Using enum to set the directory
=> [CCFPCM-654] Fix file upload

README.md
[CCFPCM-0639](https://bcdevex.atlassian.net/browse/CCFPCM-0639)
Objective: 
- Remove references to “common component” for the time being
The project name is now DROP (Discrepancy reports on payments)
Ensure consistent language is used to refer to ministry/client and types of data we are handling
terms:
Line of business (LOB)
Payment transactions
BCM (Banking & Cash Management)
Cash deposits
POS deposits
Generically, the things we’re reconciling are “records” which we apply heuristics to
=> [CCFPCM-0639]: readme update

README.md
Objective: 
[![Lifecycle:Maturing](https://img.shields.io/badge/Lifecycle-Maturing-007EC6)](<Redirect-URL>)
DROP automates the manual process of finding and reporting discrepancies between the ministry line of business transactions and Provincial Treasury's bank and cash management deposit files.
Payment-transaction data from the line-of-business represents one half of the data and is received via STFP.
Deposit data from Provincial Treasury of the Province of British Columbia is also obtained via SFTP and comes in three formats:
- TDI34 files - In-person point-of-sale (POS) transactions
- TDI17 files - Cash & cheque deposits made to the banks
- TDI34 Daily Download Files (DDF)  - Online card transactions (PayBC and ICE Pay)
Files are pushed …
=> [FIX] docs: readmeupdate

Makefile, terraform/variables.tf
[CCFPCM-0691](https://bcdevex.atlassian.net/browse/CCFPCM-0691)
Objective: 
- rename the tf state file name
=> [CCFPCM-691] state file name

.github/workflows/clear-all-data-tools.yaml, .github/workflows/s3-file-sync-manual-tools.yaml, Makefile, apps/backend/src/database/clear-dev-db.ts, terraform/clear-dev-db.tf
[CCFPCM-0697](https://bcdevex.atlassian.net/browse/CCFPCM-0697)
Objective: 
- enable manual sync/clear for tools env
=> [CCFPCM-0697] Tools sync/clear actions

apps/backend/src/database/database.module.ts, apps/backend/src/database/database.service.ts, apps/backend/src/database/migrate.ts, apps/backend/src/deposits/cash-deposit.service.ts, apps/backend/src/deposits/pos-deposit.service.ts, apps/backend/src/location/location.service.ts, apps/backend/src/transaction/transaction.service.ts, apps/backend/test/e2e/db-e2e.spec.ts, terraform/clear-dev-db.tf, terraform/lambda_migrator.tf
[CCFPCM-699](https://bcdevex.atlassian.net/browse/CCFPCM-699)
Objective: 
- resolve lambda memory exceeded error while running the seed scripts
=> [CCFPCM-699] migrate timeout

.github/workflows/deploy-tools.yml, .github/workflows/deploy-zap-dev.yaml, Makefile
Objective: 
- error deploying due to lambda rename
=> [FIX]: makefile error

apps/backend/src/parse/parse.service.ts
[CCFPCM-700](https://bcdevex.atlassian.net/browse/CCFPCM-700)
Objective: 
- ensure the error message sends the alert and is clear on the error for malformed JSON
=> [CCFPCM-700] fix: json parsing error message

apps/backend/src/constants.ts, apps/backend/src/lambdas/parser.ts, apps/backend/src/lambdas/utils/parseGarms.ts, apps/backend/src/location/entities/location.entity.ts, apps/backend/src/location/location.service.ts, apps/backend/src/notification/mail-templates.ts, apps/backend/src/notification/notification.service.ts, apps/backend/src/parse/dto/list.dto.ts, apps/backend/src/parse/parse.service.ts, apps/backend/src/parse/upload.service.ts, apps/backend/test/mocks/classes/transaction_mock.ts, apps/backend/test/mocks/mocks.ts, apps/backend/test/unit/parsing/parse-service.spec.ts
[CCFPCM-0688](https://bcdevex.atlassian.net/browse/CCFPCM-0688)
Objective: 
- create location stub
- split upload methods from parsing/validation 
- refactor parsing with generic types ?
=> [CCFPCM-688] Location stub

bin/assume.sh, bin/bastionid.sh, terraform/s3.tf, terraform/scripts/runs.sh
[CCFPCM-702](https://bcdevex.atlassian.net/browse/CCFPCM-702)
Objective: 
- remove redundant tf blocks for public acl's on S3 buckets
=> [CCFPCM-702]tf: remove redundant blocks

terraform/s3glacier.tf
[CCFPCM-646](https://bcdevex.atlassian.net/browse/CCFPCM-646)
Objective: Add tf that should be applied for S3 Glacier Vault
=> [CCFPCM-646] add tf file for S3 glacier vault

apps/backend/src/lambdas/utils/parseGarms.ts, apps/backend/src/parse/parse.service.ts, apps/backend/test/e2e/db-e2e.spec.ts
[CCFPCM-688](https://bcdevex.atlassian.net/browse/CCFPCM-688)
Objective: 
- ensure the new location id is included in the txn table when an unknown location is found/created
=> [CCFPCM-688] fix: location_id is added to the txn table for unknown locations

terraform/lambda_seeder.tf
[CCFPCM-0703](https://bcdevex.atlassian.net/browse/CCFPCM-0703)
Objective: 
- didn't push this change on the last one!
=> [CCFPCM-703] fix: increase lambda memory

Makefile, apps/backend/package.json, apps/backend/src/app.config.ts, apps/backend/src/common/documentation.ts, apps/backend/src/main.ts, docker-compose.yml, terraform/api.tf, terraform/clear-dev-db.tf, terraform/lambda_batch_reconciler.tf, terraform/lambda_dailyfilecheck.tf, terraform/lambda_migrator.tf, terraform/lambda_parser.tf, terraform/lambda_reconciler.tf, terraform/lambda_reporting.tf, terraform/lambda_seeder.tf, terraform/variables.tf
Objective: 
- on tools the report lambda was timing out - it is less likely to occur on prod as data is reconciled daily and the reports are based on this date, but for very busy months it is better to have the option to use more memory if needed
=> [CHORE] Pre-release Versioning + lambda timeout fix

.github/workflows/s3-file-sync-manual-tools.yaml, .github/workflows/s3-files-sync-dev-manual.yaml, .github/workflows/s3-files-sync.yaml
[CCFPCM-718](https://bcdevex.atlassian.net/browse/CCFPCM-718)
Objective: 
- rename prod -> prod-sync (we also have a prod-deployments env which has protections enabled)
=> [CCFPCM-718]: rename prod-sync env

terraform/clear-dev-db.tf
Objective: 
- Fix for cleardevdata lambda - this will no longer appear in test and prod
=> [FIX]: remove clear dev data func from test and prod envs
